try for loop

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,7 +34,10 @@ jobs:
           # start mainnet anvil
           nohup tilt up anvil:mainnet &
           echo waiting for tilt and anvil to be ready
-          curl -s --retry 10 --retry-delay 1 --retry-max-time 10 http://localhost:10350 > /dev/null
+          for i in {1..10}; do
+            curl -s http://localhost:10350 > /dev/null && break || echo "Attempt $i failed, trying again..."
+            sleep 1
+          done
           echo tilt is ready
           tilt wait --for=condition=Ready "uiresource/anvil:mainnet"
           echo anvil is ready
